# Generated by Django 4.2.7 on 2023-11-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_answers_options_alter_tasks_options_and_more'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='tasks',
            order_with_respect_to='test',
        ),
    ]
